[package]
name = "apartment-monitor"
version = "0.0.1"
authors = ["David LaBarbera"]

[dependencies]
rascam = { version = "0.0.2", features = ["debug"] }
rppal = { version = "0.13.1", features = ["hal"] }

[[bin]]
name = "door-monitor"
path = "src/rust/main.rs"